name: forecast_unificado120

on:
  workflow_dispatch:
  schedule:
    - cron: "20 6 * * *"   # todos los días 06:20 UTC

permissions:
  contents: write

jobs:
  run-forecast-unificado:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install pandas numpy scikit-learn joblib python-dateutil requests tensorflow requests-cache retry-requests
          fi

      - name: Run unified inference
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python forecast_unificado120.py

      - name: Commit & push output files
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Fuerza agregar solo los JSON de salida (sin tocar .gitignore)
          git add -f public/predicciones2.json public/llamadas_por_dia2.json || true

          # Si no hay cambios, no fallar
          if git diff --staged --quiet; then
            echo "No hay cambios para commitear."
            exit 0
          fi

          git commit -m "chore(unificado): actualización automática predicciones2 y llamadas_por_dia2"
          git push
