name: forecast_alertas

on:
  workflow_dispatch:
  schedule:
    - cron: "30 7 * * *"  # 07:30 UTC ≈ 04:30 Chile

permissions:
  contents: write

jobs:
  run-alertas:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies (base)
        run: |
          pip install -r requirements.txt
          # SOLO este workflow eleva scikit-learn para compatibilidad del scaler de alertas
          pip install --upgrade scikit-learn==1.6.1
          python -c "import sys, sklearn, pandas, numpy; print('Py',sys.version); print('sklearn', sklearn.__version__); print('pandas',pandas.__version__); print('numpy',numpy.__version__)"

      - name: Descargar modelos de ALERTAS desde Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Usa tu utils_release con soporte de --pattern
          python utils_release.py --owner Supervision-Inbound --repo wfneuronal --pattern alertas_clima --target models

      - name: Ejecutar inferencia climática
        run: |
          python forecast_alertas.py

      - name: Commit & Push JSON
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add public/alertas_clima.json
          git commit -m "chore(alertas): actualización automática de alertas climáticas" --allow-empty
          git push

