name: forecast_llamadas120_baseline2

on:
  workflow_dispatch:
  schedule:
    - cron: "15 6 * * *"   # 06:15 UTC todos los días (ajusta si quieres)

permissions:
  contents: write

jobs:
  run-forecast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Usa tus versiones probadas
          pip install pandas==2.2.2 numpy==1.26.4 scikit-learn==1.2.2 joblib==1.4.2 \
                      python-dateutil==2.9.0.post0 requests==2.32.3 requests-cache==1.2.0 \
                      retry-requests==2.0.0 tensorflow

      - name: Run inference (solo llamadas, sin clima)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python forecast_llamadas120_baseline2.py

      - name: Commit & push output files (force add)
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -f public/predicciones2.json public/llamadas_por_dia2.json
          git commit -m "chore(forecast): generados predicciones2.json y llamadas_por_dia2.json" --allow-empty
          git push
