name: forecast3m

# ==========================================================
# Disparadores (Triggers) del Workflow
# ==========================================================
on:
  # 1. PERMITE LA EJECUCIÓN MANUAL DESDE LA PESTAÑA "ACTIONS"
  workflow_dispatch:

  # 2. EJECUCIÓN AUTOMÁTICA PROGRAMADA
  schedule:
    - cron: "15 6 * * *"  # Se ejecuta todos los días a las 06:15 UTC

# Permisos para que la Action pueda escribir en el repositorio
permissions:
  contents: write

jobs:
  run-forecast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run inference script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python forecast3m.py

      - name: Commit & push output files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          # El siguiente comando solo hace commit si detecta cambios reales en los archivos
          git diff --quiet && git diff --staged --quiet || git commit -m "chore(forecast): actualización automática de predicciones con modelos NN"
          git push
